---
kind: pipeline
name: test-and-publish
type: docker

steps:
  - name: fetch-tags
    image: docker:git
    commands:
      - git fetch --tags

  - name: restore-cache
    image: drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    settings:
      restore: true
      mount:
        - .gcache/wrapper
        - .gcache/caches/modules-2
      cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME ]
    volumes:
      - name: host-cache
        path: /cache

  - name: check-versions
    image: openjdk:11-jdk
    environment:
      GRADLE_USER_HOME: .gcache
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    commands:
      - ./gradlew depCheck
    when:
      branch:
        exclude:
          - master
          - devops/*
      event:
        - push

  - name: unit-test
    image: openjdk:11-jdk
    environment:
      GRADLE_USER_HOME: .gcache
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
    commands:
      - echo ${DRONE_STAGE_MACHINE}
      - ./gradlew clean test check

  - name: save-cache
    image: drillster/drone-volume-cache@sha256:b82e143081dfb04ba300ce7854dfcecd31e7858e1998bf89806ec74a80a78e94
    settings:
      rebuild: true
      mount:
        - .gcache/wrapper
        - .gcache/caches/modules-2
      cache_key: [ DRONE_REPO_OWNER, DRONE_REPO_NAME ]
    volumes:
      - name: host-cache
        path: /cache

  - name: publish-to-s3
    image: openjdk:11-jdk
    environment:
      GRADLE_USER_HOME: .gcache
      GRADLE_OPTS: -Dorg.gradle.daemon=false -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false
      PUBLISH_KEY:
        from_secret: gcloud-key
    commands:
      - ./gradlew --info publish
    when:
      ref:
        - refs/heads/master

  - name: notify
    image: drillster/drone-email
    settings:
      host: email-smtp.us-east-1.amazonaws.com
      username:
        from_secret: smtp-user
      from: drone-notify@practiceinsight.io
      password:
        from_secret: smtp-password
    when:
      status: failure

  - name: cascade-to-bamboo
    image: registry.dev.wisetime.com/git
    environment:
      BAMBOO_USER:
        from_secret: bamboo-user
      BAMBOO_PASS:
        from_secret: bamboo-pass
    commands:
      - echo "Caccade to artifact via user $${BAMBOO_USER}"
      - ./bin/cascade.sh
    when:
      ref:
        - refs/heads/master

volumes:
  - name: host-cache
    host:
      # expects agent to have /tmp/cache directory created
      path: /tmp/cache

trigger:
  event:
    - push

---
kind: pipeline
name: mirror-to-github
type: docker

depends_on:
  - test-and-publish

steps:
  - name: github-push
    image: registry.dev.wisetime.com/git
    environment:
      GITHUB_SSH_KEY_B64:
        from_secret: github-ssh-key-b64
    commands:
      - ./bin/mirror.sh
    when:
      ref:
        - refs/heads/master

trigger:
  event:
    - push

---
kind: secret
name: github-ssh-key-b64
get:
  path: drone/publish/github/core-log
  name: gh-connector-java-key-b64

---
kind: secret
name: bamboo-user
get:
  path: drone/bamboo/trigger
  name: bamboo-user

---
kind: secret
name: bamboo-pass
get:
  path: drone/bamboo/trigger
  name: bamboo-pass

---
kind: secret
name: smtp-password
get:
  path: drone/notify/smtp
  name: password

---
kind: secret
name: smtp-user
get:
  path: drone/notify/smtp
  name: user

---
kind: secret
name: gcloud-key
get:
  path: drone/gcloud
  name: json_key_b64
