---
version: 2
plan:
  project-key: CAPI
  key: WCA
  name: wisetime-connector-artifact
stages:
  - ARTIFACT1:
      manual: false
      final: false
      jobs:
        - save source artifact
save source artifact:
  key: SSA
  tasks:
    - checkout:
        repository: wisetime-connector-java
        path: wisetime-connector-java
        force-clean-build: 'false'
    - script:
        interpreter: SHELL
        scripts:
          - |-
            export PROJ_NAME=wisetime-connector-java
            rm -rf $PROJ_NAME/.git && tar chfvz $PROJ_NAME-src.tgz -C $PROJ_NAME . && rm -rf $PROJ_NAME
            echo "Created tar.gz at $PROJ_NAME-src.tgz"
  artifacts:
    - name: wisetime-connector-java
      location: ./
      pattern: wisetime-connector-java-src.tgz
      shared: true
      required: true
triggers: []
branches:
  create: manually
  delete: never
  link-to-jira: true
notifications:
  - events:
      - job-failed
    recipients:
      - responsible
      - committers
labels: []
other:
  concurrent-build-plugin: system-default
---
version: 2
plan:
  key: CAPI-WCA
plan-permissions:
  - groups:
      - bamboo-build-team
    permissions:
      - view
      - edit
      - build
  - groups:
      - bamboo-admin
    permissions:
      - view
      - edit
      - build
      - clone
      - admin
  - roles:
      - logged-in
    permissions:
      - view
...
---
version: 2
deployment:
  name: _Publish wisetime-connector-java library
  source-plan: CAPI-WCA
release-naming:
  next-version-name: 1.3.11
  applies-to-branches: false
  auto-increment: true
  auto-increment-variables: []
environments:
  - Maven Central
Maven Central:
  triggers: []
  tasks:
    - clean
    - artifact-download:
        artifacts:
          - {}
    - script:
        interpreter: SHELL
        scripts:
          - |-
            tar xzf wisetime-connector-java-src.tgz
            echo "Archive extracted"
            ls -la
    - script:
        interpreter: SHELL
        scripts:
          - |-
            echo "releasing version: $bamboo_deploy_version to Maven Central"
            ./gradlew clean build publishToSonatype closeAndReleaseRepository -x test -Pversion=$bamboo_deploy_version -Dorg.gradle.internal.http.socketTimeout=60000 --info
  variables: {}
  requirements: []
  notifications: []
---
version: 2
deployment:
  name: _Publish wisetime-connector-java library
deployment-permissions:
  - groups:
      - bamboo-admin
    permissions:
      - view
      - edit
  - roles:
      - logged-in
    permissions:
      - view

environment-permissions:
  - Maven Central:
      - groups:
          - bamboo-deploy-team-prod
        permissions:
          - view
          - deploy
      - groups:
          - bamboo-admin
        permissions:
          - view
          - edit
          - deploy
...

